### ISSUE TITLE
Quest: Ember Engines Guides MVP Tracking issue

### ISSUE THREAD

**Issue by villander** [ember-engines/ember-engines.com#55]
Hello and thanks so much for helping out with the Ember Engines Guides! We need the knowledge you've gained over the years using ember-engines

# High level tracking, in progress:

This section is purely for tracking how much work we still have left to do, in a very broad sense.

## General

- [x] Almost all docs from README should be moved to ember-engines.com. Having similar but different info in both places is confusing and unmaintainable. [ issue ember-engines/ember-engines/issues/540 ]

- [x] Clarify the philosophy and intended uses for engines. [ issue #57 ]
  > Is the "Why Use Engines?" section on http://ember-engines.com/ sufficient?

- [x] Update the "Engines Roadmap" section [ issue #56 ]
  > Link to the 1.0 Roadmap

- [x] Include a section on using engines with Fastboot. [ issue #58 ]

- [x] Testing section is completely blank. We need to discuss what's possible today. [ issue #59 ]

- [x]  Make Ember Engines more public for beginners in Ember.js [ issue ember-learn/guides-source/issues/701 ]

- [x]  Upgrade documentation with Ember CLI Addon Docs, improving UX [ issue #50 ]

## Building Engines

- [x] Clarify that engines should always be built together with their host app and other engines, _regardless of whether they are lazy or eager_. This is required for hosts to understand and properly bundle engine dependencies and routes. [ issue #56 ]

- [x] Explain what will happen when there are dependency mismatches between different engines and/or their host app. [ issue #60 ]

- [x] Explain the dependency deduping that is currently performed. [ issue #16 ]

- [ ] Explain the manual verification of dependencies that is needed _right now_. [ issue #61 ]

- [ ] Include a few examples that lists a host app and engines, as well a few dependencies (common and shared) to illustrate points. [ issue #62 ]

**Comment by lifeart** [comment]
Engines example repo - https://github.com/catz/eng-test

**Comment by villander** [comment]
thanks @lifeart I'll do a awesome demo with this work, adding more UI/UX.

**Comment by abhilashlr** [comment]
Also an architecture diagram on how engines work?

**Comment by villander** [comment]
> Also an architecture diagram on how engines work?

this will be expose on #62, it already tracked on this issue. We need of great examples with ember-engines to clarify the purpose and how it works
